#ifndef _ALTERA_CPU_1B_P1_MM_BRIDGE_0_H_
#define _ALTERA_CPU_1B_P1_MM_BRIDGE_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'FTOP_MSOC' in
 * file '../SUPERSCALAR_18/FTOP_MSOC.sopcinfo'.
 */

/*
 * This file contains macros for module 'CPU_1b_p1_mm_bridge_0' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fifo_qb_p1_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QB_P1_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QB_P1_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QB_P1_IN_CSR_COMPONENT_NAME fifo_qb_p1
#define FIFO_QB_P1_IN_CSR_BASE 0x0
#define FIFO_QB_P1_IN_CSR_SPAN 32
#define FIFO_QB_P1_IN_CSR_END 0x1f
#define FIFO_QB_P1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QB_P1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QB_P1_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_QB_P1_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_QB_P1_IN_CSR_ERROR_WIDTH 8
#define FIFO_QB_P1_IN_CSR_FIFO_DEPTH 32
#define FIFO_QB_P1_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_QB_P1_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_QB_P1_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QB_P1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QB_P1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_QB_P1_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_QB_P1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_QB_P1_IN_CSR_USE_IRQ 0
#define FIFO_QB_P1_IN_CSR_USE_PACKET 1
#define FIFO_QB_P1_IN_CSR_USE_READ_CONTROL 0
#define FIFO_QB_P1_IN_CSR_USE_REGISTER 0
#define FIFO_QB_P1_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qa_p1_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QA_P1_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QA_P1_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QA_P1_IN_CSR_COMPONENT_NAME fifo_qa_p1
#define FIFO_QA_P1_IN_CSR_BASE 0x20
#define FIFO_QA_P1_IN_CSR_SPAN 32
#define FIFO_QA_P1_IN_CSR_END 0x3f
#define FIFO_QA_P1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QA_P1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QA_P1_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_QA_P1_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_QA_P1_IN_CSR_ERROR_WIDTH 8
#define FIFO_QA_P1_IN_CSR_FIFO_DEPTH 128
#define FIFO_QA_P1_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_QA_P1_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_QA_P1_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QA_P1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QA_P1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_QA_P1_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_QA_P1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_QA_P1_IN_CSR_USE_IRQ 0
#define FIFO_QA_P1_IN_CSR_USE_PACKET 1
#define FIFO_QA_P1_IN_CSR_USE_READ_CONTROL 0
#define FIFO_QA_P1_IN_CSR_USE_REGISTER 0
#define FIFO_QA_P1_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qa_p1_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QA_P1_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QA_P1_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QA_P1_OUT_COMPONENT_NAME fifo_qa_p1
#define FIFO_QA_P1_OUT_BASE 0x40
#define FIFO_QA_P1_OUT_SPAN 4
#define FIFO_QA_P1_OUT_END 0x43
#define FIFO_QA_P1_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QA_P1_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QA_P1_OUT_BITS_PER_SYMBOL 16
#define FIFO_QA_P1_OUT_CHANNEL_WIDTH 8
#define FIFO_QA_P1_OUT_ERROR_WIDTH 8
#define FIFO_QA_P1_OUT_FIFO_DEPTH 128
#define FIFO_QA_P1_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_QA_P1_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_QA_P1_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QA_P1_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QA_P1_OUT_USE_AVALONST_SINK 0
#define FIFO_QA_P1_OUT_USE_AVALONST_SOURCE 0
#define FIFO_QA_P1_OUT_USE_BACKPRESSURE 1
#define FIFO_QA_P1_OUT_USE_IRQ 0
#define FIFO_QA_P1_OUT_USE_PACKET 1
#define FIFO_QA_P1_OUT_USE_READ_CONTROL 0
#define FIFO_QA_P1_OUT_USE_REGISTER 0
#define FIFO_QA_P1_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qb_p1_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QB_P1_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QB_P1_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QB_P1_IN_COMPONENT_NAME fifo_qb_p1
#define FIFO_QB_P1_IN_BASE 0x44
#define FIFO_QB_P1_IN_SPAN 4
#define FIFO_QB_P1_IN_END 0x47
#define FIFO_QB_P1_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QB_P1_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QB_P1_IN_BITS_PER_SYMBOL 16
#define FIFO_QB_P1_IN_CHANNEL_WIDTH 8
#define FIFO_QB_P1_IN_ERROR_WIDTH 8
#define FIFO_QB_P1_IN_FIFO_DEPTH 32
#define FIFO_QB_P1_IN_SINGLE_CLOCK_MODE 1
#define FIFO_QB_P1_IN_SYMBOLS_PER_BEAT 2
#define FIFO_QB_P1_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QB_P1_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QB_P1_IN_USE_AVALONST_SINK 0
#define FIFO_QB_P1_IN_USE_AVALONST_SOURCE 0
#define FIFO_QB_P1_IN_USE_BACKPRESSURE 1
#define FIFO_QB_P1_IN_USE_IRQ 0
#define FIFO_QB_P1_IN_USE_PACKET 1
#define FIFO_QB_P1_IN_USE_READ_CONTROL 0
#define FIFO_QB_P1_IN_USE_REGISTER 0
#define FIFO_QB_P1_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'mem_info', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'MEM_INFO_'.
 * The prefix is the slave descriptor.
 */
#define MEM_INFO_COMPONENT_TYPE altera_avalon_onchip_memory2
#define MEM_INFO_COMPONENT_NAME mem_info
#define MEM_INFO_BASE 0x10000
#define MEM_INFO_SPAN 1024
#define MEM_INFO_END 0x103ff
#define MEM_INFO_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEM_INFO_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEM_INFO_CONTENTS_INFO ""
#define MEM_INFO_DUAL_PORT 0
#define MEM_INFO_GUI_RAM_BLOCK_TYPE AUTO
#define MEM_INFO_INIT_CONTENTS_FILE FTOP_MSOC_mem_info
#define MEM_INFO_INIT_MEM_CONTENT 1
#define MEM_INFO_INSTANCE_ID NONE
#define MEM_INFO_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEM_INFO_RAM_BLOCK_TYPE AUTO
#define MEM_INFO_READ_DURING_WRITE_MODE DONT_CARE
#define MEM_INFO_SINGLE_CLOCK_OP 0
#define MEM_INFO_SIZE_MULTIPLE 1
#define MEM_INFO_SIZE_VALUE 1024
#define MEM_INFO_WRITABLE 1
#define MEM_INFO_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define MEM_INFO_MEMORY_INFO_GENERATE_DAT_SYM 1
#define MEM_INFO_MEMORY_INFO_GENERATE_HEX 1
#define MEM_INFO_MEMORY_INFO_HAS_BYTE_LANE 0
#define MEM_INFO_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define MEM_INFO_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define MEM_INFO_MEMORY_INFO_MEM_INIT_FILENAME FTOP_MSOC_mem_info


#endif /* _ALTERA_CPU_1B_P1_MM_BRIDGE_0_H_ */
