#ifndef _ALTERA_CPU_1C_P2_H_
#define _ALTERA_CPU_1C_P2_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'FTOP_MSOC' in
 * file 'FTOP_MSOC.sopcinfo'.
 */

/*
 * This file contains macros for module 'CPU_1c_p2' and devices
 * connected to the following master:
 *   mm_bridge_0_m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fifo_qb_p2_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QB_P2_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QB_P2_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QB_P2_IN_CSR_COMPONENT_NAME fifo_qb_p2
#define FIFO_QB_P2_IN_CSR_BASE 0x0
#define FIFO_QB_P2_IN_CSR_SPAN 32
#define FIFO_QB_P2_IN_CSR_END 0x1f
#define FIFO_QB_P2_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QB_P2_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QB_P2_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_QB_P2_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_QB_P2_IN_CSR_ERROR_WIDTH 8
#define FIFO_QB_P2_IN_CSR_FIFO_DEPTH 32
#define FIFO_QB_P2_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_QB_P2_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_QB_P2_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QB_P2_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QB_P2_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_QB_P2_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_QB_P2_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_QB_P2_IN_CSR_USE_IRQ 0
#define FIFO_QB_P2_IN_CSR_USE_PACKET 1
#define FIFO_QB_P2_IN_CSR_USE_READ_CONTROL 0
#define FIFO_QB_P2_IN_CSR_USE_REGISTER 0
#define FIFO_QB_P2_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qc_p2_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QC_P2_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QC_P2_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QC_P2_IN_CSR_COMPONENT_NAME fifo_qc_p2
#define FIFO_QC_P2_IN_CSR_BASE 0x20
#define FIFO_QC_P2_IN_CSR_SPAN 32
#define FIFO_QC_P2_IN_CSR_END 0x3f
#define FIFO_QC_P2_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QC_P2_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QC_P2_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_QC_P2_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_QC_P2_IN_CSR_ERROR_WIDTH 8
#define FIFO_QC_P2_IN_CSR_FIFO_DEPTH 32
#define FIFO_QC_P2_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_QC_P2_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_QC_P2_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QC_P2_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QC_P2_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_QC_P2_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_QC_P2_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_QC_P2_IN_CSR_USE_IRQ 0
#define FIFO_QC_P2_IN_CSR_USE_PACKET 1
#define FIFO_QC_P2_IN_CSR_USE_READ_CONTROL 0
#define FIFO_QC_P2_IN_CSR_USE_REGISTER 0
#define FIFO_QC_P2_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qc_p2_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QC_P2_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QC_P2_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QC_P2_IN_COMPONENT_NAME fifo_qc_p2
#define FIFO_QC_P2_IN_BASE 0x40
#define FIFO_QC_P2_IN_SPAN 4
#define FIFO_QC_P2_IN_END 0x43
#define FIFO_QC_P2_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QC_P2_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QC_P2_IN_BITS_PER_SYMBOL 16
#define FIFO_QC_P2_IN_CHANNEL_WIDTH 8
#define FIFO_QC_P2_IN_ERROR_WIDTH 8
#define FIFO_QC_P2_IN_FIFO_DEPTH 32
#define FIFO_QC_P2_IN_SINGLE_CLOCK_MODE 1
#define FIFO_QC_P2_IN_SYMBOLS_PER_BEAT 2
#define FIFO_QC_P2_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QC_P2_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QC_P2_IN_USE_AVALONST_SINK 0
#define FIFO_QC_P2_IN_USE_AVALONST_SOURCE 0
#define FIFO_QC_P2_IN_USE_BACKPRESSURE 1
#define FIFO_QC_P2_IN_USE_IRQ 0
#define FIFO_QC_P2_IN_USE_PACKET 1
#define FIFO_QC_P2_IN_USE_READ_CONTROL 0
#define FIFO_QC_P2_IN_USE_REGISTER 0
#define FIFO_QC_P2_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_qb_p2_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_QB_P2_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_QB_P2_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_QB_P2_OUT_COMPONENT_NAME fifo_qb_p2
#define FIFO_QB_P2_OUT_BASE 0x44
#define FIFO_QB_P2_OUT_SPAN 4
#define FIFO_QB_P2_OUT_END 0x47
#define FIFO_QB_P2_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_QB_P2_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_QB_P2_OUT_BITS_PER_SYMBOL 16
#define FIFO_QB_P2_OUT_CHANNEL_WIDTH 8
#define FIFO_QB_P2_OUT_ERROR_WIDTH 8
#define FIFO_QB_P2_OUT_FIFO_DEPTH 32
#define FIFO_QB_P2_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_QB_P2_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_QB_P2_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_QB_P2_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_QB_P2_OUT_USE_AVALONST_SINK 0
#define FIFO_QB_P2_OUT_USE_AVALONST_SOURCE 0
#define FIFO_QB_P2_OUT_USE_BACKPRESSURE 1
#define FIFO_QB_P2_OUT_USE_IRQ 0
#define FIFO_QB_P2_OUT_USE_PACKET 1
#define FIFO_QB_P2_OUT_USE_READ_CONTROL 0
#define FIFO_QB_P2_OUT_USE_REGISTER 0
#define FIFO_QB_P2_OUT_USE_WRITE_CONTROL 1


#endif /* _ALTERA_CPU_1C_P2_H_ */
