#ifndef _ALTERA_CPU_1D_H_
#define _ALTERA_CPU_1D_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'SDR_MSOC' in
 * file './SDR_MSOC.sopcinfo'.
 */

/*
 * This file contains macros for module 'cpu_1d' and devices
 * connected to the following masters:
 *   data_master
 *   instruction_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'cpu_1d', class 'altera_nios2_gen2'.
 * The macros have no prefix.
 */
#define BIG_ENDIAN 0
#define BREAK_ADDR 0x8000820
#define CPU_ARCH_NIOS2_R1 
#define CPU_FREQ 75000000
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x00000000
#define CPU_IMPLEMENTATION "tiny"
#define DATA_ADDR_WIDTH 28
#define DCACHE_LINE_SIZE 0
#define DCACHE_LINE_SIZE_LOG2 0
#define DCACHE_SIZE 0
#define EXCEPTION_ADDR 0x60020
#define FLASH_ACCELERATOR_LINES 0
#define FLASH_ACCELERATOR_LINE_SIZE 0
#define FLUSHDA_SUPPORTED 
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 0
#define HARDWARE_MULX_PRESENT 0
#define HAS_DEBUG_CORE 1
#define HAS_DEBUG_STUB 
#define HAS_ILLEGAL_INSTRUCTION_EXCEPTION 
#define HAS_JMPI_INSTRUCTION 
#define ICACHE_LINE_SIZE 0
#define ICACHE_LINE_SIZE_LOG2 0
#define ICACHE_SIZE 0
#define INST_ADDR_WIDTH 28
#define OCI_VERSION 1
#define RESET_ADDR 0x60000

/*
 * Macros for device 'sdram_controller', class 'altera_avalon_new_sdram_controller'
 * The macros are prefixed with 'SDRAM_CONTROLLER_'.
 * The prefix is the slave descriptor.
 */
#define SDRAM_CONTROLLER_COMPONENT_TYPE altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_COMPONENT_NAME sdram_controller
#define SDRAM_CONTROLLER_BASE 0x0
#define SDRAM_CONTROLLER_SPAN 134217728
#define SDRAM_CONTROLLER_END 0x7ffffff
#define SDRAM_CONTROLLER_CAS_LATENCY 3
#define SDRAM_CONTROLLER_CONTENTS_INFO 
#define SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_REFRESH_PERIOD 15.625
#define SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 25
#define SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_SHARED_DATA 0
#define SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_T_AC 6.0
#define SDRAM_CONTROLLER_T_MRD 3
#define SDRAM_CONTROLLER_T_RCD 20.0
#define SDRAM_CONTROLLER_T_RFC 70.0
#define SDRAM_CONTROLLER_T_RP 20.0
#define SDRAM_CONTROLLER_T_WR 14.0
#define SDRAM_CONTROLLER_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SDRAM_CONTROLLER_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SDRAM_CONTROLLER_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32

/*
 * Macros for device 'fifo_1d_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1D_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1D_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1D_IN_CSR_COMPONENT_NAME fifo_1d
#define FIFO_1D_IN_CSR_BASE 0x8001000
#define FIFO_1D_IN_CSR_SPAN 32
#define FIFO_1D_IN_CSR_END 0x800101f
#define FIFO_1D_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1D_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1D_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_1D_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1D_IN_CSR_ERROR_WIDTH 8
#define FIFO_1D_IN_CSR_FIFO_DEPTH 32
#define FIFO_1D_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_1D_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_1D_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1D_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1D_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1D_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1D_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1D_IN_CSR_USE_IRQ 0
#define FIFO_1D_IN_CSR_USE_PACKET 1
#define FIFO_1D_IN_CSR_USE_READ_CONTROL 0
#define FIFO_1D_IN_CSR_USE_REGISTER 0
#define FIFO_1D_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_1c_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1C_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1C_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1C_IN_CSR_COMPONENT_NAME fifo_1c
#define FIFO_1C_IN_CSR_BASE 0x8001020
#define FIFO_1C_IN_CSR_SPAN 32
#define FIFO_1C_IN_CSR_END 0x800103f
#define FIFO_1C_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1C_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1C_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_1C_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1C_IN_CSR_ERROR_WIDTH 8
#define FIFO_1C_IN_CSR_FIFO_DEPTH 32
#define FIFO_1C_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_1C_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_1C_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1C_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1C_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1C_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1C_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1C_IN_CSR_USE_IRQ 0
#define FIFO_1C_IN_CSR_USE_PACKET 1
#define FIFO_1C_IN_CSR_USE_READ_CONTROL 0
#define FIFO_1C_IN_CSR_USE_REGISTER 0
#define FIFO_1C_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_4_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_4_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_4_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_4_IN_CSR_COMPONENT_NAME fifo_q_4
#define FIFO_Q_4_IN_CSR_BASE 0x8001040
#define FIFO_Q_4_IN_CSR_SPAN 32
#define FIFO_Q_4_IN_CSR_END 0x800105f
#define FIFO_Q_4_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_4_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_4_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_4_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_4_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_4_IN_CSR_FIFO_DEPTH 32
#define FIFO_Q_4_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_4_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_4_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_4_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_4_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_4_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_4_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_4_IN_CSR_USE_IRQ 0
#define FIFO_Q_4_IN_CSR_USE_PACKET 1
#define FIFO_Q_4_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_4_IN_CSR_USE_REGISTER 0
#define FIFO_Q_4_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'timer_1d', class 'altera_avalon_timer'
 * The macros are prefixed with 'TIMER_1D_'.
 * The prefix is the slave descriptor.
 */
#define TIMER_1D_COMPONENT_TYPE altera_avalon_timer
#define TIMER_1D_COMPONENT_NAME timer_1d
#define TIMER_1D_BASE 0x8001060
#define TIMER_1D_SPAN 32
#define TIMER_1D_END 0x800107f
#define TIMER_1D_IRQ 1
#define TIMER_1D_ALWAYS_RUN 0
#define TIMER_1D_COUNTER_SIZE 32
#define TIMER_1D_FIXED_PERIOD 0
#define TIMER_1D_FREQ 75000000
#define TIMER_1D_LOAD_VALUE 74999
#define TIMER_1D_MULT 0.001
#define TIMER_1D_PERIOD 1
#define TIMER_1D_PERIOD_UNITS ms
#define TIMER_1D_RESET_OUTPUT 0
#define TIMER_1D_SNAPSHOT 1
#define TIMER_1D_TICKS_PER_SEC 1000
#define TIMER_1D_TIMEOUT_PULSE_OUTPUT 0

/*
 * Macros for device 'sysid_1d', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_1D_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_1D_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_1D_COMPONENT_NAME sysid_1d
#define SYSID_1D_BASE 0x8001080
#define SYSID_1D_SPAN 8
#define SYSID_1D_END 0x8001087
#define SYSID_1D_ID 29
#define SYSID_1D_TIMESTAMP 1718692765

/*
 * Macros for device 'jtag_uart_1d', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_1D_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_1D_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_1D_COMPONENT_NAME jtag_uart_1d
#define JTAG_UART_1D_BASE 0x8001088
#define JTAG_UART_1D_SPAN 8
#define JTAG_UART_1D_END 0x800108f
#define JTAG_UART_1D_IRQ 16
#define JTAG_UART_1D_READ_DEPTH 64
#define JTAG_UART_1D_READ_THRESHOLD 8
#define JTAG_UART_1D_WRITE_DEPTH 64
#define JTAG_UART_1D_WRITE_THRESHOLD 8

/*
 * Macros for device 'fifo_q_4_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_4_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_4_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_4_OUT_COMPONENT_NAME fifo_q_4
#define FIFO_Q_4_OUT_BASE 0x8001090
#define FIFO_Q_4_OUT_SPAN 4
#define FIFO_Q_4_OUT_END 0x8001093
#define FIFO_Q_4_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_4_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_4_OUT_BITS_PER_SYMBOL 16
#define FIFO_Q_4_OUT_CHANNEL_WIDTH 8
#define FIFO_Q_4_OUT_ERROR_WIDTH 8
#define FIFO_Q_4_OUT_FIFO_DEPTH 32
#define FIFO_Q_4_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_Q_4_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_Q_4_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_4_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_4_OUT_USE_AVALONST_SINK 0
#define FIFO_Q_4_OUT_USE_AVALONST_SOURCE 0
#define FIFO_Q_4_OUT_USE_BACKPRESSURE 1
#define FIFO_Q_4_OUT_USE_IRQ 0
#define FIFO_Q_4_OUT_USE_PACKET 1
#define FIFO_Q_4_OUT_USE_READ_CONTROL 0
#define FIFO_Q_4_OUT_USE_REGISTER 0
#define FIFO_Q_4_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_1c_out', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1C_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1C_OUT_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1C_OUT_COMPONENT_NAME fifo_1c
#define FIFO_1C_OUT_BASE 0x8001094
#define FIFO_1C_OUT_SPAN 4
#define FIFO_1C_OUT_END 0x8001097
#define FIFO_1C_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1C_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1C_OUT_BITS_PER_SYMBOL 16
#define FIFO_1C_OUT_CHANNEL_WIDTH 8
#define FIFO_1C_OUT_ERROR_WIDTH 8
#define FIFO_1C_OUT_FIFO_DEPTH 32
#define FIFO_1C_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_1C_OUT_SYMBOLS_PER_BEAT 2
#define FIFO_1C_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1C_OUT_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1C_OUT_USE_AVALONST_SINK 0
#define FIFO_1C_OUT_USE_AVALONST_SOURCE 0
#define FIFO_1C_OUT_USE_BACKPRESSURE 1
#define FIFO_1C_OUT_USE_IRQ 0
#define FIFO_1C_OUT_USE_PACKET 1
#define FIFO_1C_OUT_USE_READ_CONTROL 0
#define FIFO_1C_OUT_USE_REGISTER 0
#define FIFO_1C_OUT_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_1d_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_1D_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_1D_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_1D_IN_COMPONENT_NAME fifo_1d
#define FIFO_1D_IN_BASE 0x8001098
#define FIFO_1D_IN_SPAN 4
#define FIFO_1D_IN_END 0x800109b
#define FIFO_1D_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1D_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1D_IN_BITS_PER_SYMBOL 16
#define FIFO_1D_IN_CHANNEL_WIDTH 8
#define FIFO_1D_IN_ERROR_WIDTH 8
#define FIFO_1D_IN_FIFO_DEPTH 32
#define FIFO_1D_IN_SINGLE_CLOCK_MODE 1
#define FIFO_1D_IN_SYMBOLS_PER_BEAT 2
#define FIFO_1D_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1D_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1D_IN_USE_AVALONST_SINK 0
#define FIFO_1D_IN_USE_AVALONST_SOURCE 0
#define FIFO_1D_IN_USE_BACKPRESSURE 1
#define FIFO_1D_IN_USE_IRQ 0
#define FIFO_1D_IN_USE_PACKET 1
#define FIFO_1D_IN_USE_READ_CONTROL 0
#define FIFO_1D_IN_USE_REGISTER 0
#define FIFO_1D_IN_USE_WRITE_CONTROL 1


#endif /* _ALTERA_CPU_1D_H_ */
