#ifndef _ALTERA_CPU_H_
#define _ALTERA_CPU_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'SDR_MSOC' in
 * file './SDR_MSOC.sopcinfo'.
 */

/*
 * This file contains macros for module 'cpu' and devices
 * connected to the following masters:
 *   data_master
 *   instruction_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'cpu', class 'altera_nios2_gen2'.
 * The macros have no prefix.
 */
#define BIG_ENDIAN 0
#define BREAK_ADDR 0x8000820
#define CPU_ARCH_NIOS2_R1 
#define CPU_FREQ 75000000
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x00000000
#define CPU_IMPLEMENTATION "tiny"
#define DATA_ADDR_WIDTH 28
#define DCACHE_LINE_SIZE 0
#define DCACHE_LINE_SIZE_LOG2 0
#define DCACHE_SIZE 0
#define EXCEPTION_ADDR 0xc0020
#define FLASH_ACCELERATOR_LINES 0
#define FLASH_ACCELERATOR_LINE_SIZE 0
#define FLUSHDA_SUPPORTED 
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 0
#define HARDWARE_MULX_PRESENT 0
#define HAS_DEBUG_CORE 1
#define HAS_DEBUG_STUB 
#define HAS_ILLEGAL_INSTRUCTION_EXCEPTION 
#define HAS_JMPI_INSTRUCTION 
#define ICACHE_LINE_SIZE 0
#define ICACHE_LINE_SIZE_LOG2 0
#define ICACHE_SIZE 0
#define INST_ADDR_WIDTH 28
#define OCI_VERSION 1
#define RESET_ADDR 0xc0000

/*
 * Macros for device 'sdram_controller', class 'altera_avalon_new_sdram_controller'
 * The macros are prefixed with 'SDRAM_CONTROLLER_'.
 * The prefix is the slave descriptor.
 */
#define SDRAM_CONTROLLER_COMPONENT_TYPE altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_COMPONENT_NAME sdram_controller
#define SDRAM_CONTROLLER_BASE 0x0
#define SDRAM_CONTROLLER_SPAN 134217728
#define SDRAM_CONTROLLER_END 0x7ffffff
#define SDRAM_CONTROLLER_CAS_LATENCY 3
#define SDRAM_CONTROLLER_CONTENTS_INFO 
#define SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_REFRESH_PERIOD 15.625
#define SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 25
#define SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_SHARED_DATA 0
#define SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_T_AC 6.0
#define SDRAM_CONTROLLER_T_MRD 3
#define SDRAM_CONTROLLER_T_RCD 20.0
#define SDRAM_CONTROLLER_T_RFC 70.0
#define SDRAM_CONTROLLER_T_RP 20.0
#define SDRAM_CONTROLLER_T_WR 14.0
#define SDRAM_CONTROLLER_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SDRAM_CONTROLLER_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SDRAM_CONTROLLER_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32

/*
 * Macros for device 'fifo_q_6_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_6_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_6_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_6_IN_CSR_COMPONENT_NAME fifo_q_6
#define FIFO_Q_6_IN_CSR_BASE 0x8001000
#define FIFO_Q_6_IN_CSR_SPAN 32
#define FIFO_Q_6_IN_CSR_END 0x800101f
#define FIFO_Q_6_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_6_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_6_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_6_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_6_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_6_IN_CSR_FIFO_DEPTH 32
#define FIFO_Q_6_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_6_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_6_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_6_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_6_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_6_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_6_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_6_IN_CSR_USE_IRQ 0
#define FIFO_Q_6_IN_CSR_USE_PACKET 1
#define FIFO_Q_6_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_6_IN_CSR_USE_REGISTER 0
#define FIFO_Q_6_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_5_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_5_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_5_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_5_IN_CSR_COMPONENT_NAME fifo_q_5
#define FIFO_Q_5_IN_CSR_BASE 0x8001020
#define FIFO_Q_5_IN_CSR_SPAN 32
#define FIFO_Q_5_IN_CSR_END 0x800103f
#define FIFO_Q_5_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_5_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_5_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_5_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_5_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_5_IN_CSR_FIFO_DEPTH 32
#define FIFO_Q_5_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_5_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_5_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_5_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_5_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_5_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_5_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_5_IN_CSR_USE_IRQ 0
#define FIFO_Q_5_IN_CSR_USE_PACKET 1
#define FIFO_Q_5_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_5_IN_CSR_USE_REGISTER 0
#define FIFO_Q_5_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_4_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_4_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_4_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_4_IN_CSR_COMPONENT_NAME fifo_q_4
#define FIFO_Q_4_IN_CSR_BASE 0x8001040
#define FIFO_Q_4_IN_CSR_SPAN 32
#define FIFO_Q_4_IN_CSR_END 0x800105f
#define FIFO_Q_4_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_4_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_4_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_4_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_4_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_4_IN_CSR_FIFO_DEPTH 32
#define FIFO_Q_4_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_4_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_4_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_4_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_4_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_4_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_4_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_4_IN_CSR_USE_IRQ 0
#define FIFO_Q_4_IN_CSR_USE_PACKET 1
#define FIFO_Q_4_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_4_IN_CSR_USE_REGISTER 0
#define FIFO_Q_4_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_3_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_3_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_3_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_3_IN_CSR_COMPONENT_NAME fifo_q_3
#define FIFO_Q_3_IN_CSR_BASE 0x8001060
#define FIFO_Q_3_IN_CSR_SPAN 32
#define FIFO_Q_3_IN_CSR_END 0x800107f
#define FIFO_Q_3_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_3_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_3_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_3_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_3_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_3_IN_CSR_FIFO_DEPTH 256
#define FIFO_Q_3_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_3_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_3_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_3_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_3_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_3_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_3_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_3_IN_CSR_USE_IRQ 0
#define FIFO_Q_3_IN_CSR_USE_PACKET 1
#define FIFO_Q_3_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_3_IN_CSR_USE_REGISTER 0
#define FIFO_Q_3_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_2_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_2_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_2_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_2_IN_CSR_COMPONENT_NAME fifo_q_2
#define FIFO_Q_2_IN_CSR_BASE 0x8001080
#define FIFO_Q_2_IN_CSR_SPAN 32
#define FIFO_Q_2_IN_CSR_END 0x800109f
#define FIFO_Q_2_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_2_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_2_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_2_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_2_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_2_IN_CSR_FIFO_DEPTH 256
#define FIFO_Q_2_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_2_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_2_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_2_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_2_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_2_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_2_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_2_IN_CSR_USE_IRQ 0
#define FIFO_Q_2_IN_CSR_USE_PACKET 1
#define FIFO_Q_2_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_2_IN_CSR_USE_REGISTER 0
#define FIFO_Q_2_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_1_in_csr', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_1_IN_CSR_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_1_IN_CSR_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_1_IN_CSR_COMPONENT_NAME fifo_q_1
#define FIFO_Q_1_IN_CSR_BASE 0x80010a0
#define FIFO_Q_1_IN_CSR_SPAN 32
#define FIFO_Q_1_IN_CSR_END 0x80010bf
#define FIFO_Q_1_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_1_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_1_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_Q_1_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_Q_1_IN_CSR_ERROR_WIDTH 8
#define FIFO_Q_1_IN_CSR_FIFO_DEPTH 256
#define FIFO_Q_1_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_Q_1_IN_CSR_SYMBOLS_PER_BEAT 2
#define FIFO_Q_1_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_1_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_1_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_Q_1_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_Q_1_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_Q_1_IN_CSR_USE_IRQ 0
#define FIFO_Q_1_IN_CSR_USE_PACKET 1
#define FIFO_Q_1_IN_CSR_USE_READ_CONTROL 0
#define FIFO_Q_1_IN_CSR_USE_REGISTER 0
#define FIFO_Q_1_IN_CSR_USE_WRITE_CONTROL 1

/*
 * Macros for device 'timer', class 'altera_avalon_timer'
 * The macros are prefixed with 'TIMER_'.
 * The prefix is the slave descriptor.
 */
#define TIMER_COMPONENT_TYPE altera_avalon_timer
#define TIMER_COMPONENT_NAME timer
#define TIMER_BASE 0x80010c0
#define TIMER_SPAN 32
#define TIMER_END 0x80010df
#define TIMER_IRQ 1
#define TIMER_ALWAYS_RUN 0
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 0
#define TIMER_FREQ 75000000
#define TIMER_LOAD_VALUE 74999
#define TIMER_MULT 0.001
#define TIMER_PERIOD 1
#define TIMER_PERIOD_UNITS ms
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_TICKS_PER_SEC 1000
#define TIMER_TIMEOUT_PULSE_OUTPUT 0

/*
 * Macros for device 'pll', class 'altpll'
 * The macros are prefixed with 'PLL_'.
 * The prefix is the slave descriptor.
 */
#define PLL_COMPONENT_TYPE altpll
#define PLL_COMPONENT_NAME pll
#define PLL_BASE 0x80010e0
#define PLL_SPAN 16
#define PLL_END 0x80010ef

/*
 * Macros for device 'sys_id', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYS_ID_'.
 * The prefix is the slave descriptor.
 */
#define SYS_ID_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYS_ID_COMPONENT_NAME sys_id
#define SYS_ID_BASE 0x80010f0
#define SYS_ID_SPAN 8
#define SYS_ID_END 0x80010f7
#define SYS_ID_ID 26
#define SYS_ID_TIMESTAMP 1718692765

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x80010f8
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x80010ff
#define JTAG_UART_IRQ 16
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'fifo_q_6_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_6_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_6_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_6_IN_COMPONENT_NAME fifo_q_6
#define FIFO_Q_6_IN_BASE 0x8001100
#define FIFO_Q_6_IN_SPAN 4
#define FIFO_Q_6_IN_END 0x8001103
#define FIFO_Q_6_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_6_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_6_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_6_IN_CHANNEL_WIDTH 8
#define FIFO_Q_6_IN_ERROR_WIDTH 8
#define FIFO_Q_6_IN_FIFO_DEPTH 32
#define FIFO_Q_6_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_6_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_6_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_6_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_6_IN_USE_AVALONST_SINK 0
#define FIFO_Q_6_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_6_IN_USE_BACKPRESSURE 1
#define FIFO_Q_6_IN_USE_IRQ 0
#define FIFO_Q_6_IN_USE_PACKET 1
#define FIFO_Q_6_IN_USE_READ_CONTROL 0
#define FIFO_Q_6_IN_USE_REGISTER 0
#define FIFO_Q_6_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_5_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_5_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_5_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_5_IN_COMPONENT_NAME fifo_q_5
#define FIFO_Q_5_IN_BASE 0x8001104
#define FIFO_Q_5_IN_SPAN 4
#define FIFO_Q_5_IN_END 0x8001107
#define FIFO_Q_5_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_5_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_5_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_5_IN_CHANNEL_WIDTH 8
#define FIFO_Q_5_IN_ERROR_WIDTH 8
#define FIFO_Q_5_IN_FIFO_DEPTH 32
#define FIFO_Q_5_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_5_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_5_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_5_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_5_IN_USE_AVALONST_SINK 0
#define FIFO_Q_5_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_5_IN_USE_BACKPRESSURE 1
#define FIFO_Q_5_IN_USE_IRQ 0
#define FIFO_Q_5_IN_USE_PACKET 1
#define FIFO_Q_5_IN_USE_READ_CONTROL 0
#define FIFO_Q_5_IN_USE_REGISTER 0
#define FIFO_Q_5_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_4_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_4_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_4_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_4_IN_COMPONENT_NAME fifo_q_4
#define FIFO_Q_4_IN_BASE 0x8001108
#define FIFO_Q_4_IN_SPAN 4
#define FIFO_Q_4_IN_END 0x800110b
#define FIFO_Q_4_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_4_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_4_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_4_IN_CHANNEL_WIDTH 8
#define FIFO_Q_4_IN_ERROR_WIDTH 8
#define FIFO_Q_4_IN_FIFO_DEPTH 32
#define FIFO_Q_4_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_4_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_4_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_4_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_4_IN_USE_AVALONST_SINK 0
#define FIFO_Q_4_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_4_IN_USE_BACKPRESSURE 1
#define FIFO_Q_4_IN_USE_IRQ 0
#define FIFO_Q_4_IN_USE_PACKET 1
#define FIFO_Q_4_IN_USE_READ_CONTROL 0
#define FIFO_Q_4_IN_USE_REGISTER 0
#define FIFO_Q_4_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_3_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_3_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_3_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_3_IN_COMPONENT_NAME fifo_q_3
#define FIFO_Q_3_IN_BASE 0x800110c
#define FIFO_Q_3_IN_SPAN 4
#define FIFO_Q_3_IN_END 0x800110f
#define FIFO_Q_3_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_3_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_3_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_3_IN_CHANNEL_WIDTH 8
#define FIFO_Q_3_IN_ERROR_WIDTH 8
#define FIFO_Q_3_IN_FIFO_DEPTH 256
#define FIFO_Q_3_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_3_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_3_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_3_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_3_IN_USE_AVALONST_SINK 0
#define FIFO_Q_3_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_3_IN_USE_BACKPRESSURE 1
#define FIFO_Q_3_IN_USE_IRQ 0
#define FIFO_Q_3_IN_USE_PACKET 1
#define FIFO_Q_3_IN_USE_READ_CONTROL 0
#define FIFO_Q_3_IN_USE_REGISTER 0
#define FIFO_Q_3_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_2_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_2_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_2_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_2_IN_COMPONENT_NAME fifo_q_2
#define FIFO_Q_2_IN_BASE 0x8001110
#define FIFO_Q_2_IN_SPAN 4
#define FIFO_Q_2_IN_END 0x8001113
#define FIFO_Q_2_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_2_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_2_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_2_IN_CHANNEL_WIDTH 8
#define FIFO_Q_2_IN_ERROR_WIDTH 8
#define FIFO_Q_2_IN_FIFO_DEPTH 256
#define FIFO_Q_2_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_2_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_2_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_2_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_2_IN_USE_AVALONST_SINK 0
#define FIFO_Q_2_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_2_IN_USE_BACKPRESSURE 1
#define FIFO_Q_2_IN_USE_IRQ 0
#define FIFO_Q_2_IN_USE_PACKET 1
#define FIFO_Q_2_IN_USE_READ_CONTROL 0
#define FIFO_Q_2_IN_USE_REGISTER 0
#define FIFO_Q_2_IN_USE_WRITE_CONTROL 1

/*
 * Macros for device 'fifo_q_1_in', class 'altera_avalon_fifo'
 * The macros are prefixed with 'FIFO_Q_1_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_Q_1_IN_COMPONENT_TYPE altera_avalon_fifo
#define FIFO_Q_1_IN_COMPONENT_NAME fifo_q_1
#define FIFO_Q_1_IN_BASE 0x8001114
#define FIFO_Q_1_IN_SPAN 4
#define FIFO_Q_1_IN_END 0x8001117
#define FIFO_Q_1_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_Q_1_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_Q_1_IN_BITS_PER_SYMBOL 16
#define FIFO_Q_1_IN_CHANNEL_WIDTH 8
#define FIFO_Q_1_IN_ERROR_WIDTH 8
#define FIFO_Q_1_IN_FIFO_DEPTH 256
#define FIFO_Q_1_IN_SINGLE_CLOCK_MODE 1
#define FIFO_Q_1_IN_SYMBOLS_PER_BEAT 2
#define FIFO_Q_1_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_Q_1_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_Q_1_IN_USE_AVALONST_SINK 0
#define FIFO_Q_1_IN_USE_AVALONST_SOURCE 0
#define FIFO_Q_1_IN_USE_BACKPRESSURE 1
#define FIFO_Q_1_IN_USE_IRQ 0
#define FIFO_Q_1_IN_USE_PACKET 1
#define FIFO_Q_1_IN_USE_READ_CONTROL 0
#define FIFO_Q_1_IN_USE_REGISTER 0
#define FIFO_Q_1_IN_USE_WRITE_CONTROL 1


#endif /* _ALTERA_CPU_H_ */
